create table public.reviews (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  establecimiento text null,
  "user" text null,
  evento_nombre text null,
  fechaevento timestamp with time zone null,
  notas text null,
  stars numeric null,
  constraint reviews_pkey primary key (id)
) TABLESPACE pg_default;
